### ISSUE TITLE
Cannot decrypt access key

### ISSUE THREAD

**Issue by hufhend** [semaphoreui/charts#6]
Hi, I have it set up almost by default. After setting it up, it runs normally, but after some time, maybe the next day, nothing works. The log shows the following message:
```
Server is running

2025/06/17 22:08:33 http: panic serving 10.233.111.169:38616: cannot decrypt access key, perhaps encryption key was changed
goroutine 66 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1947 +0xbe
```

![Image](https://github.com/user-attachments/assets/15c2c54b-8ed6-4b0f-b50b-7a241bc523bf)

Mode of deployment:
```
# from chart https://artifacthub.io/packages/helm/semaphoreui/semaphore
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2025061600"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: semaphore
    server: https://kubernetes.default.svc/
  project: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://semaphoreui.github.io/charts
    chart: semaphore
    targetRevision: 16.0.0

    helm:
      valuesObject:
        extraEnvVariables:
          TZ: "Europe/Prague"
          SEMAPHORE_WEB_ROOT: https://semaphore.example.cz/

        database:
          type: postgres
          host: postgresql
          port: 5432
          usernameFromSecret: false
          passwordKey: password
          existingSecret: postgresql
        postgresql:
          enabled: true
          auth:
            password: change-me
          primary:
            persistence:
              enabled: true
              accessMode: ReadWriteMany
              size: 5Gi
              storageClass: "nfs-csi"
            extraEnvVars:
            - name: TZ
              value: "Europe/Prague"

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-body-size: 500m
          hosts:
            - host: semaphore.example.cz
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: semaphore.example-tls
              hosts:
                - semaphore.example.cz

        persistence:
          storageClass: "nfs-csi"
          accessModes:
            - ReadWriteOnce
        general:
          additionalPythonPackages:
            - kubernetes>=32.0.0
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - s-hp110-dc1
```
