### ISSUE TITLE
Allow passing of oidc provider block as Kubernetes Secret

### ISSUE THREAD

**Issue by C0rn3rphr34k** [semaphoreui/charts#9]
To be able to properly secure the `client_id` and `client_secret` of the oidc provider config block when committing the values.yaml to git, I'd like to suggest adding a feature that allows to pass in the whole config block, e.g. `keycloak` from a Kubernetes Secret (which in turn may be created with the help of sealed-secrets).

So instead of:
```
oidc:
  # -- Enable oidc authentication
  enable: true

  # -- Dictionary of oidc providers
  providers:
    keycloak:
      display_name: Keycloak
      provider_url: https://test-keycloak.example.com/auth
      redirect_url: https://semaphoreui.example.com/api/auth/oidc/keycloak/redirect
      client_id: ************ # redacted
      client_secret: ************ # redacted
      username_claim: username
      name_claim: name
      email_claim: email
```

something along the lines of:
```
oidc:
  # -- Enable oidc authentication
  enable: true

  # -- Dictionary of oidc providers
  providers:
    existingSecret: <secret-name-here>
```

Let me know if you have any questions and thank you for providing a helm chart for Semaphore UI
